# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 673228a38e2e48ab46c978311e1a1078bb1b53270a42d24526d88f38c0d88ad019ade418719f19cfa43925ee710fbd94ae7b0dd95b4be9405a6e147cd68e36d4

test:
  secret_key_base: 01353ce2d9f7e34cf953b80c218fe9cdbb52eb47b87d6d401844390f6821769885f453a1dec14f35c460fdd15988d8cfe31d0c8be550b52c1e75ae67a25ed922

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
